### ISSUE TITLE
[Nhóm#08] - Lỗi phi chức năng - không có thuộc tính "alt" trong thẻ img - ở trang https://cntt.ueh.edu.vn/

### ISSUE THREAD

**Issue by 31191026186** [UEHMonQAQC/ST_K45_02#287]
a. Browser: Google Chrome
b. Kết quả thực tế :
![image](https://user-images.githubusercontent.com/92743913/145423374-4fb6c48a-75d1-4089-b23c-10493850443c.png)
![image](https://user-images.githubusercontent.com/92743913/145423455-88589702-be0f-487c-94eb-69baa5ba36b3.png)
c. kết quả mong đợi: thêm thuộc tính "alt" vào thẻ img.
d. các bước phát hiện lỗi.
i. #1 truy cập trang web https://validator.w3.org/
![Screenshot (32)](https://user-images.githubusercontent.com/92743913/145423946-6ae2b722-11f2-48af-9282-3c66a533b9b7.png)
ii. #2 nhập link  https://cntt.ueh.edu.vn/ vào ô address và click check
iii. #3 xuất hiện lỗi.
![image](https://user-images.githubusercontent.com/92743913/145424891-e7a903b1-bbcf-464c-b0bf-ffeb3724f56b.png)
![image](https://user-images.githubusercontent.com/92743913/145424968-b5a7d531-1d2f-4e04-a60e-c2869d52b476.png)

**Comment by 31191024852** [comment]
Này không được tính là lỗi nha, Vì thuộc tính alt thì trong lúc code người code có thể không thiết lập vì nó không ảnh hưởng đến CSDL. Cảm ơn bạn
